version: "3.8"

services:
  app:
    depends_on:
      - book-db
    restart: on-failure
    image: booking-app
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://book-db:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true",
      "spring.datasource.username" : "$MYSQLDB_USER",
      "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
      "spring.jpa.properties.hibernate.ddl-auto" : "validate"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

  book-db:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      - MySQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 30s
      timeout: 30s
      retries: 3
      